//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1.D3Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class News : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentSampleField;
        
        private int NewsIDField;
        
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        private int ImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private int ArticleTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ContentSample {
            get {
                return this.ContentSampleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentSampleField, value) != true)) {
                    this.ContentSampleField = value;
                    this.RaisePropertyChanged("ContentSample");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NewsID {
            get {
                return this.NewsIDField;
            }
            set {
                if ((this.NewsIDField.Equals(value) != true)) {
                    this.NewsIDField = value;
                    this.RaisePropertyChanged("NewsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ImageType {
            get {
                return this.ImageTypeField;
            }
            set {
                if ((this.ImageTypeField.Equals(value) != true)) {
                    this.ImageTypeField = value;
                    this.RaisePropertyChanged("ImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ArticleTypeID {
            get {
                return this.ArticleTypeIDField;
            }
            set {
                if ((this.ArticleTypeIDField.Equals(value) != true)) {
                    this.ArticleTypeIDField = value;
                    this.RaisePropertyChanged("ArticleTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewsForIPhone", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NewsForIPhone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NewsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeField;
        
        private int ImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentSampleField;
        
        private int ArticleTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NewsID {
            get {
                return this.NewsIDField;
            }
            set {
                if ((this.NewsIDField.Equals(value) != true)) {
                    this.NewsIDField = value;
                    this.RaisePropertyChanged("NewsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ImageType {
            get {
                return this.ImageTypeField;
            }
            set {
                if ((this.ImageTypeField.Equals(value) != true)) {
                    this.ImageTypeField = value;
                    this.RaisePropertyChanged("ImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ContentSample {
            get {
                return this.ContentSampleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentSampleField, value) != true)) {
                    this.ContentSampleField = value;
                    this.RaisePropertyChanged("ContentSample");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ArticleTypeID {
            get {
                return this.ArticleTypeIDField;
            }
            set {
                if ((this.ArticleTypeIDField.Equals(value) != true)) {
                    this.ArticleTypeIDField = value;
                    this.RaisePropertyChanged("ArticleTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="D3Service.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetNewsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        TestProject1.D3Service.GetNewsResponse GetNews(TestProject1.D3Service.GetNewsRequest request);
        
        // CODEGEN: Generating message contract since element name GetNewsSimpleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsSimple", ReplyAction="*")]
        TestProject1.D3Service.GetNewsSimpleResponse GetNewsSimple(TestProject1.D3Service.GetNewsSimpleRequest request);
        
        // CODEGEN: Generating message contract since element name filter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsForIPhone", ReplyAction="*")]
        TestProject1.D3Service.GetNewsForIPhoneResponse GetNewsForIPhone(TestProject1.D3Service.GetNewsForIPhoneRequest request);
        
        // CODEGEN: Generating message contract since element name GetNewsArticleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsArticle", ReplyAction="*")]
        TestProject1.D3Service.GetNewsArticleResponse GetNewsArticle(TestProject1.D3Service.GetNewsArticleRequest request);
        
        // CODEGEN: Generating message contract since element name GetNewsArticleForIPhoneResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsArticleForIPhone", ReplyAction="*")]
        TestProject1.D3Service.GetNewsArticleForIPhoneResponse GetNewsArticleForIPhone(TestProject1.D3Service.GetNewsArticleForIPhoneRequest request);
        
        // CODEGEN: Generating message contract since element name filter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestNewsArticleForIPhone", ReplyAction="*")]
        TestProject1.D3Service.GetLatestNewsArticleForIPhoneResponse GetLatestNewsArticleForIPhone(TestProject1.D3Service.GetLatestNewsArticleForIPhoneRequest request);
        
        // CODEGEN: Generating message contract since element name GetRandomArticleForIPhoneResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomArticleForIPhone", ReplyAction="*")]
        TestProject1.D3Service.GetRandomArticleForIPhoneResponse GetRandomArticleForIPhone(TestProject1.D3Service.GetRandomArticleForIPhoneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNews", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsRequestBody Body;
        
        public GetNewsRequest() {
        }
        
        public GetNewsRequest(TestProject1.D3Service.GetNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int startIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int takeCount;
        
        public GetNewsRequestBody() {
        }
        
        public GetNewsRequestBody(int startIndex, int takeCount) {
            this.startIndex = startIndex;
            this.takeCount = takeCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsResponseBody Body;
        
        public GetNewsResponse() {
        }
        
        public GetNewsResponse(TestProject1.D3Service.GetNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestProject1.D3Service.News[] GetNewsResult;
        
        public GetNewsResponseBody() {
        }
        
        public GetNewsResponseBody(TestProject1.D3Service.News[] GetNewsResult) {
            this.GetNewsResult = GetNewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsSimpleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsSimple", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsSimpleRequestBody Body;
        
        public GetNewsSimpleRequest() {
        }
        
        public GetNewsSimpleRequest(TestProject1.D3Service.GetNewsSimpleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsSimpleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int startIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int takeCount;
        
        public GetNewsSimpleRequestBody() {
        }
        
        public GetNewsSimpleRequestBody(int startIndex, int takeCount) {
            this.startIndex = startIndex;
            this.takeCount = takeCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsSimpleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsSimpleResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsSimpleResponseBody Body;
        
        public GetNewsSimpleResponse() {
        }
        
        public GetNewsSimpleResponse(TestProject1.D3Service.GetNewsSimpleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsSimpleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestProject1.D3Service.News[] GetNewsSimpleResult;
        
        public GetNewsSimpleResponseBody() {
        }
        
        public GetNewsSimpleResponseBody(TestProject1.D3Service.News[] GetNewsSimpleResult) {
            this.GetNewsSimpleResult = GetNewsSimpleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsForIPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsForIPhone", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsForIPhoneRequestBody Body;
        
        public GetNewsForIPhoneRequest() {
        }
        
        public GetNewsForIPhoneRequest(TestProject1.D3Service.GetNewsForIPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsForIPhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int startIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int takeCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filter;
        
        public GetNewsForIPhoneRequestBody() {
        }
        
        public GetNewsForIPhoneRequestBody(int startIndex, int takeCount, string filter) {
            this.startIndex = startIndex;
            this.takeCount = takeCount;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsForIPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsForIPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsForIPhoneResponseBody Body;
        
        public GetNewsForIPhoneResponse() {
        }
        
        public GetNewsForIPhoneResponse(TestProject1.D3Service.GetNewsForIPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsForIPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestProject1.D3Service.NewsForIPhone[] GetNewsForIPhoneResult;
        
        public GetNewsForIPhoneResponseBody() {
        }
        
        public GetNewsForIPhoneResponseBody(TestProject1.D3Service.NewsForIPhone[] GetNewsForIPhoneResult) {
            this.GetNewsForIPhoneResult = GetNewsForIPhoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsArticleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsArticle", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsArticleRequestBody Body;
        
        public GetNewsArticleRequest() {
        }
        
        public GetNewsArticleRequest(TestProject1.D3Service.GetNewsArticleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsArticleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int articleID;
        
        public GetNewsArticleRequestBody() {
        }
        
        public GetNewsArticleRequestBody(int articleID) {
            this.articleID = articleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsArticleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsArticleResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsArticleResponseBody Body;
        
        public GetNewsArticleResponse() {
        }
        
        public GetNewsArticleResponse(TestProject1.D3Service.GetNewsArticleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsArticleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestProject1.D3Service.News GetNewsArticleResult;
        
        public GetNewsArticleResponseBody() {
        }
        
        public GetNewsArticleResponseBody(TestProject1.D3Service.News GetNewsArticleResult) {
            this.GetNewsArticleResult = GetNewsArticleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsArticleForIPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsArticleForIPhone", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsArticleForIPhoneRequestBody Body;
        
        public GetNewsArticleForIPhoneRequest() {
        }
        
        public GetNewsArticleForIPhoneRequest(TestProject1.D3Service.GetNewsArticleForIPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsArticleForIPhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int articleID;
        
        public GetNewsArticleForIPhoneRequestBody() {
        }
        
        public GetNewsArticleForIPhoneRequestBody(int articleID) {
            this.articleID = articleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsArticleForIPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsArticleForIPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetNewsArticleForIPhoneResponseBody Body;
        
        public GetNewsArticleForIPhoneResponse() {
        }
        
        public GetNewsArticleForIPhoneResponse(TestProject1.D3Service.GetNewsArticleForIPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsArticleForIPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestProject1.D3Service.News GetNewsArticleForIPhoneResult;
        
        public GetNewsArticleForIPhoneResponseBody() {
        }
        
        public GetNewsArticleForIPhoneResponseBody(TestProject1.D3Service.News GetNewsArticleForIPhoneResult) {
            this.GetNewsArticleForIPhoneResult = GetNewsArticleForIPhoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatestNewsArticleForIPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatestNewsArticleForIPhone", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetLatestNewsArticleForIPhoneRequestBody Body;
        
        public GetLatestNewsArticleForIPhoneRequest() {
        }
        
        public GetLatestNewsArticleForIPhoneRequest(TestProject1.D3Service.GetLatestNewsArticleForIPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLatestNewsArticleForIPhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filter;
        
        public GetLatestNewsArticleForIPhoneRequestBody() {
        }
        
        public GetLatestNewsArticleForIPhoneRequestBody(string filter) {
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatestNewsArticleForIPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatestNewsArticleForIPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetLatestNewsArticleForIPhoneResponseBody Body;
        
        public GetLatestNewsArticleForIPhoneResponse() {
        }
        
        public GetLatestNewsArticleForIPhoneResponse(TestProject1.D3Service.GetLatestNewsArticleForIPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLatestNewsArticleForIPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestProject1.D3Service.News GetLatestNewsArticleForIPhoneResult;
        
        public GetLatestNewsArticleForIPhoneResponseBody() {
        }
        
        public GetLatestNewsArticleForIPhoneResponseBody(TestProject1.D3Service.News GetLatestNewsArticleForIPhoneResult) {
            this.GetLatestNewsArticleForIPhoneResult = GetLatestNewsArticleForIPhoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomArticleForIPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomArticleForIPhone", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetRandomArticleForIPhoneRequestBody Body;
        
        public GetRandomArticleForIPhoneRequest() {
        }
        
        public GetRandomArticleForIPhoneRequest(TestProject1.D3Service.GetRandomArticleForIPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRandomArticleForIPhoneRequestBody {
        
        public GetRandomArticleForIPhoneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomArticleForIPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomArticleForIPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestProject1.D3Service.GetRandomArticleForIPhoneResponseBody Body;
        
        public GetRandomArticleForIPhoneResponse() {
        }
        
        public GetRandomArticleForIPhoneResponse(TestProject1.D3Service.GetRandomArticleForIPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomArticleForIPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestProject1.D3Service.NewsForIPhone GetRandomArticleForIPhoneResult;
        
        public GetRandomArticleForIPhoneResponseBody() {
        }
        
        public GetRandomArticleForIPhoneResponseBody(TestProject1.D3Service.NewsForIPhone GetRandomArticleForIPhoneResult) {
            this.GetRandomArticleForIPhoneResult = GetRandomArticleForIPhoneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : TestProject1.D3Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<TestProject1.D3Service.ServiceSoap>, TestProject1.D3Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProject1.D3Service.GetNewsResponse TestProject1.D3Service.ServiceSoap.GetNews(TestProject1.D3Service.GetNewsRequest request) {
            return base.Channel.GetNews(request);
        }
        
        public TestProject1.D3Service.News[] GetNews(int startIndex, int takeCount) {
            TestProject1.D3Service.GetNewsRequest inValue = new TestProject1.D3Service.GetNewsRequest();
            inValue.Body = new TestProject1.D3Service.GetNewsRequestBody();
            inValue.Body.startIndex = startIndex;
            inValue.Body.takeCount = takeCount;
            TestProject1.D3Service.GetNewsResponse retVal = ((TestProject1.D3Service.ServiceSoap)(this)).GetNews(inValue);
            return retVal.Body.GetNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProject1.D3Service.GetNewsSimpleResponse TestProject1.D3Service.ServiceSoap.GetNewsSimple(TestProject1.D3Service.GetNewsSimpleRequest request) {
            return base.Channel.GetNewsSimple(request);
        }
        
        public TestProject1.D3Service.News[] GetNewsSimple(int startIndex, int takeCount) {
            TestProject1.D3Service.GetNewsSimpleRequest inValue = new TestProject1.D3Service.GetNewsSimpleRequest();
            inValue.Body = new TestProject1.D3Service.GetNewsSimpleRequestBody();
            inValue.Body.startIndex = startIndex;
            inValue.Body.takeCount = takeCount;
            TestProject1.D3Service.GetNewsSimpleResponse retVal = ((TestProject1.D3Service.ServiceSoap)(this)).GetNewsSimple(inValue);
            return retVal.Body.GetNewsSimpleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProject1.D3Service.GetNewsForIPhoneResponse TestProject1.D3Service.ServiceSoap.GetNewsForIPhone(TestProject1.D3Service.GetNewsForIPhoneRequest request) {
            return base.Channel.GetNewsForIPhone(request);
        }
        
        public TestProject1.D3Service.NewsForIPhone[] GetNewsForIPhone(int startIndex, int takeCount, string filter) {
            TestProject1.D3Service.GetNewsForIPhoneRequest inValue = new TestProject1.D3Service.GetNewsForIPhoneRequest();
            inValue.Body = new TestProject1.D3Service.GetNewsForIPhoneRequestBody();
            inValue.Body.startIndex = startIndex;
            inValue.Body.takeCount = takeCount;
            inValue.Body.filter = filter;
            TestProject1.D3Service.GetNewsForIPhoneResponse retVal = ((TestProject1.D3Service.ServiceSoap)(this)).GetNewsForIPhone(inValue);
            return retVal.Body.GetNewsForIPhoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProject1.D3Service.GetNewsArticleResponse TestProject1.D3Service.ServiceSoap.GetNewsArticle(TestProject1.D3Service.GetNewsArticleRequest request) {
            return base.Channel.GetNewsArticle(request);
        }
        
        public TestProject1.D3Service.News GetNewsArticle(int articleID) {
            TestProject1.D3Service.GetNewsArticleRequest inValue = new TestProject1.D3Service.GetNewsArticleRequest();
            inValue.Body = new TestProject1.D3Service.GetNewsArticleRequestBody();
            inValue.Body.articleID = articleID;
            TestProject1.D3Service.GetNewsArticleResponse retVal = ((TestProject1.D3Service.ServiceSoap)(this)).GetNewsArticle(inValue);
            return retVal.Body.GetNewsArticleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProject1.D3Service.GetNewsArticleForIPhoneResponse TestProject1.D3Service.ServiceSoap.GetNewsArticleForIPhone(TestProject1.D3Service.GetNewsArticleForIPhoneRequest request) {
            return base.Channel.GetNewsArticleForIPhone(request);
        }
        
        public TestProject1.D3Service.News GetNewsArticleForIPhone(int articleID) {
            TestProject1.D3Service.GetNewsArticleForIPhoneRequest inValue = new TestProject1.D3Service.GetNewsArticleForIPhoneRequest();
            inValue.Body = new TestProject1.D3Service.GetNewsArticleForIPhoneRequestBody();
            inValue.Body.articleID = articleID;
            TestProject1.D3Service.GetNewsArticleForIPhoneResponse retVal = ((TestProject1.D3Service.ServiceSoap)(this)).GetNewsArticleForIPhone(inValue);
            return retVal.Body.GetNewsArticleForIPhoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProject1.D3Service.GetLatestNewsArticleForIPhoneResponse TestProject1.D3Service.ServiceSoap.GetLatestNewsArticleForIPhone(TestProject1.D3Service.GetLatestNewsArticleForIPhoneRequest request) {
            return base.Channel.GetLatestNewsArticleForIPhone(request);
        }
        
        public TestProject1.D3Service.News GetLatestNewsArticleForIPhone(string filter) {
            TestProject1.D3Service.GetLatestNewsArticleForIPhoneRequest inValue = new TestProject1.D3Service.GetLatestNewsArticleForIPhoneRequest();
            inValue.Body = new TestProject1.D3Service.GetLatestNewsArticleForIPhoneRequestBody();
            inValue.Body.filter = filter;
            TestProject1.D3Service.GetLatestNewsArticleForIPhoneResponse retVal = ((TestProject1.D3Service.ServiceSoap)(this)).GetLatestNewsArticleForIPhone(inValue);
            return retVal.Body.GetLatestNewsArticleForIPhoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProject1.D3Service.GetRandomArticleForIPhoneResponse TestProject1.D3Service.ServiceSoap.GetRandomArticleForIPhone(TestProject1.D3Service.GetRandomArticleForIPhoneRequest request) {
            return base.Channel.GetRandomArticleForIPhone(request);
        }
        
        public TestProject1.D3Service.NewsForIPhone GetRandomArticleForIPhone() {
            TestProject1.D3Service.GetRandomArticleForIPhoneRequest inValue = new TestProject1.D3Service.GetRandomArticleForIPhoneRequest();
            inValue.Body = new TestProject1.D3Service.GetRandomArticleForIPhoneRequestBody();
            TestProject1.D3Service.GetRandomArticleForIPhoneResponse retVal = ((TestProject1.D3Service.ServiceSoap)(this)).GetRandomArticleForIPhone(inValue);
            return retVal.Body.GetRandomArticleForIPhoneResult;
        }
    }
}
